# Generated by Django 5.1.7 on 2025-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_time', models.IntegerField(help_text='Transaction time in 24-hour format (0-23)')),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('device_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_fraud', models.BooleanField(blank=True, null=True)),
                ('risk_percentage', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
