# Generated by Django 5.1.7 on 2025-03-30 05:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_alter_bankaccount_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_account_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', 'Enter a valid account number (9-18 digits)')])),
                ('receiver_bank_name', models.CharField(max_length=100)),
                ('receiver_ifsc', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', 'Enter a valid IFSC code')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='detector.bankaccount')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
