# Generated by Django 5.1.7 on 2025-03-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_banktransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='receiver_ifsc',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='detector.bankaccount'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='receiver_ifsc_code',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='receiver_account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='receiver_bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='detector.bankaccount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
