# Generated by Django 5.1.7 on 2025-03-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_alter_banktransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-transaction_date']},
        ),
    ]
