# Generated by Django 5.1.7 on 2025-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_alter_banktransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=100)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Invalid credentials', max_length=100)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='device_id',
            field=models.CharField(max_length=100),
        ),
    ]
